Repository RightCapitalHQ/frontend-libraries, pull requests merged in 2023-10, with the labels that each got.

#21 feat: add date-helpers package
  .github/workflows/ci.yml
  change/@rightcapital-date-helpers-4ff1d37d-1a8b-4f01-b06b-88be8a9238c9.json
  packages/date-helpers/CHANGELOG.json
  packages/date-helpers/CHANGELOG.md
  packages/date-helpers/README.md
  packages/date-helpers/__tests__/date-helpers.test.ts
  packages/date-helpers/docs/.nojekyll
  packages/date-helpers/docs/README.md
  packages/date-helpers/docs/classes/DateHelpers.md
  packages/date-helpers/docs/modules.md
  packages/date-helpers/jest.config.js
  packages/date-helpers/package.json
  packages/date-helpers/src/date-helpers.ts
  packages/date-helpers/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#24 fix(date-helpers): correct package entry points and include TypeDoc in _.d.ts_ for npm release
  change/@rightcapital-date-helpers-ebcbc19d-09cb-426b-88d2-3b8003247078.json
  packages/date-helpers/package.json
  packages/date-helpers/tsconfig.json
Labels: bugfix

#27 chore(exceptions): improve the type declaration to qualify strict type check
  packages/exceptions/src/exceptions/base.exception.ts
Labels: enhancement

#28 chore: add repository link to packages
  change/@rightcapital-date-helpers-d7cbdc56-1c31-4511-af33-28fc8325fecc.json
  change/@rightcapital-exceptions-b400cd37-2ed2-4140-b2c6-58df8e8c16eb.json
  packages/date-helpers/package.json
  packages/exceptions/package.json
Labels: maintenance
